### ISSUE TITLE
Kubernetes redundancy support

### ISSUE THREAD

**Issue by NaveLevi** [CleanSpeak/cleanspeak-containers#1]
Hi, we're trying to migrate our cleanspeak to kubernetes using the manifests from this repo.
With one replica count, everything seems to be working, but when I try to increase the [cleanspeak deployment](https://github.com/CleanSpeak/cleanspeak-containers/blob/master/kubernetes/deployments/cleanspeak-deployment.yaml) replica count to 3, everything breaks. 

Login through the admin page doesn't work most of the time, and when it does work you get kicked a few seconds after, I assume it's because I get directed to a different pod with each request and it's not supported.

Any suggestions?
Thanks

**Comment by NaveLevi** [comment]
The issue was on my side, closing

Edit: adding stickiness cookie on the ingress is what fixed the issue
```
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "stickounet"
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
```
